packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.4.5
    superjson: ^2.2.6
    zod: ^3.25.76
  trpc:
    '@trpc/client': ^11.17.0
    '@trpc/server': ^11.17.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
  vitest: 4.1.10
  vite-plus: 0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
