packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.4.5
    superjson: ^2.2.6
    zod: ^3.25.76
  trpc:
    '@trpc/client': ^11.17.0
    '@trpc/server': ^11.17.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67
  vite-plus: 0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67
  vitest: 5.0.1
overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
